{{cookiecutter.project_slug}}/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
{% if cookiecutter.multiple_languages == 'y' %}
from django.conf.urls.i18n import i18n_patterns
{% endif %}
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.views.generic import TemplateView
from django.views import defaults as default_views

{% if cookiecutter.cms == 'djangocms' -%}
from cms.sitemaps import CMSSitemap
{% elif cookiecutter.cms == 'wagtail' -%}
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailsearch import urls as wagtailsearch_urls
{%- endif %}


{% if cookiecutter.cms == 'djangocms' -%}
admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]
{% elif cookiecutter.cms == 'wagtail' %}
urlpatterns = [
    url(r'^plain-admin/', include(admin.site.urls)),

    url(r'^cms-admin/', include(wagtailadmin_urls)),
    url(r'^search/', include(wagtailsearch_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    # Optional URL for including your own vanilla Django urls/views
    # url(r'', include('myapp.urls')),
]
{% else %}
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('{{ cookiecutter.project_slug }}.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
]
{%- endif %}

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]


{% if cookiecutter.multiple_languages %}urlpatterns += i18n_patterns({% else %}urlpatterns += [{% endif %}
{% if cookiecutter.cms == 'djangocms' -%}
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    # url(r'^reviews/', include('reviews.urls', namespace='reviews')),  # NOQA
    # url(r'^', include('djangocms_forms.urls')),
    url(r'^', include('cms.urls')),
{% elif cookiecutter.cms == 'wagtail' %}
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's serving mechanism
    url(r'', include(wagtail_urls)),
{% endif %}
{% if cookiecutter.multiple_languages == 'y' %}){% else %}]{% endif %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

{{cookiecutter.project_slug}}/home/models.py
{% if cookiecutter.cms == 'wagtail' %}
from wagtail.wagtailadmin.edit_handlers import FieldPanel, StreamFieldPanel
from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import RichTextField, StreamField
from wagtail.wagtailembeds.blocks import EmbedBlock
from wagtail.wagtaildocs.blocks import DocumentChooserBlock
from wagtail.wagtailimages.blocks import ImageChooserBlock


class HomePage(Page):
    intro = RichTextField(blank=True)

    body = StreamField([
        ('text', blocks.RichTextBlock()),
        ('blockquote', blocks.BlockQuoteBlock()),
        ('image', ImageChooserBlock(template='wagtail_blocks/image.html')),
        ('document', DocumentChooserBlock()),
        ('embed', EmbedBlock(template='wagtail_blocks/embed.html')),
    ], blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('intro'),
        StreamFieldPanel('body'),
    ]
{% endif %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    # name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = []

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/403_csrf.html
{% raw %}{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/base.html
{% if cookiecutter.cms == 'djangocms' %}{% raw %}
  {% load cms_tags sekizai_tags %}
  {% load menu_tags %}
{% endraw %}
{% endif -%}

{%- raw %}{% load staticfiles i18n {% endraw %}{% if cookiecutter.use_compressor == "y" %}compress{% endif %}{% raw %}%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
      {% endraw %}{% if cookiecutter.cms == 'djangocms' %}{% raw %}
        <title>
          {% block title %}{% page_attribute "page_title" %}{% endblock %}
        </title>
        {% block head_seo %}
          <meta name="description" content="{% page_attribute 'meta_description' %}">
        {% endblock %}
      {% endraw %}{% else %}{% raw %}
        {% block title %}<title>{% endraw %}{{ cookiecutter.project_name }}{% raw %}</title>{% endblock %}
      {% endraw %}{% endif %}{% raw %}

    {% block head_social %}
      {% include "blocks/og.html" with item=feincms_page %}
    {% endblock %}

    {% block head_social_image %}
      {% include "blocks/og_image.html" with item=feincms_page %}
    {% endblock %}

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    {% endraw %}{% if cookiecutter.bootstrap_version == '3' %}
      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->
    {%- elif cookiecutter.bootstrap_version == '4' %}
      <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
      <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
      <![endif]-->
    {%- endif %}{% raw %}

    {% block css %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:300|" rel="stylesheet">
    {% endblock %}

    {% block head_css %}
      {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% compress css %}{% endraw %}{% endif %}{% raw %}
      <link href="{% static "sass/{% endraw %}{{cookiecutter.project_slug}}{% raw %}.scss" %}?v={{ version }}" 
            rel="stylesheet" media="all" type="text/x-scss">
      {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% endcompress %}{% endraw %}{% endif %}{% raw %}

      {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% compress css %}{% endraw %}{% endif %}{% raw %}
      <link href="{% static "slick-carousel/slick/slick.css" %}"
        rel="stylesheet" media="all" type="text/css">
      <link href="{% static "sass/{% endraw %}{{cookiecutter.project_slug}}{% raw %}-slick-theme.scss" %}?v={{ version }}" 
        rel="stylesheet" media="all" type="text/x-scss">
      {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% endcompress %}{% endraw %}{% endif %}{% raw %}

    {% endblock %}

    {% endraw %}{% if cookiecutter.cms == 'djangocms' %}{% raw %}
    {% render_block "css" %}
    {% endraw %}{% endif %}{% raw %}
  </head>

  <body class="{% block body_class %}bg-white{% endblock %}">
  {% endraw %}{% if cookiecutter.cms == 'djangocms' %}{% raw %}
  {% cms_toolbar %}
  {% endraw %}{% endif %}{% raw %}
  <div class="wrapper" id="wrapper">
    {% block header %}
      {% include "blocks/header.html" %}
    {% endblock header %}

    {% block menu %}
      {% include "blocks/menu.html" %}
    {% endblock menu %}

    {% block breadcrumb %}
    {% endblock %}

    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    </div>

    {% block content_header %}
      {# <h1 class="text-center">{% page_attribute "page_title" %}</h1> #}
    {% endblock %}

    {# do not remove this div, it's required for short_content_footer.js! #}
    <div class="content">
    {% block content %}
    {% endblock content %}
    </div>

    {% block footer %}
      {% include "blocks/footer.html" %}
    {% endblock footer %}

    {% block modal %}{% endblock modal %}

    {# Placed at the end of the document so the pages load faster #}
    {% block body_end_js %}
    {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% compress js %}{% endraw %}{% endif %}{% raw %}
    <script src="{% static "jquery/dist/jquery.min.js" %}" 
      type="text/javascript"></script>

    {% endraw %}{% if cookiecutter.bootstrap_version == '3' %}
      {% raw %}
        <script src="{% static "bootstrap-sass/assets/javascripts/bootstrap.min.js" %}" 
          type="text/javascript"></script>
      {% endraw %}
    {% elif cookiecutter.bootstrap_version == '4' %} 
      {% raw %}
        <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}" 
          type="text/javascript"></script>
      {% endraw %}
    {% endif %}{% raw %}
    {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% endcompress %}{% endraw %}{% endif %}{% raw %}

    {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% compress js %}{% endraw %}{% endif %}{% raw %}
    <script src="{% static "slick-carousel/slick/slick.min.js" %}" 
      type="text/javascript"></script>
    <script src="{% static "js/slick_tweaks.js" %}?v={{ version }}"></script>
    <script src="{% static "js/short_content_footer.js" %}?v=3.0"></script>
    <script src="{% static "matchHeight/dist/jquery.matchHeight-min.js" %}" 
      type="text/javascript"></script>
    <script src="{% static "js/same_height.js" %}" 
      type="text/javascript"></script>
    {% endraw %}{% if cookiecutter.use_compressor == "y" %}{% raw %}{% endcompress %}{% endraw %}{% endif %}{% raw %}
    {% endblock body_end_js %}

    {% endraw %}{% if cookiecutter.cms == 'djangocms' %}{% raw %}
    {% render_block "js" %}
    {% endraw %}{% endif %}{% raw %}
  </body>
</html>
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/footer.html
{% raw %}
{% comment %}
{% load cms_tags %}
{% endcomment %}

{% block footer %}
<footer>
  <p class="py-10 text-center">
    {% endraw %}{{ cookiecutter.project_name }}&copy;&nbsp;{% raw %} {% now "Y" %}
  </p>
</footer>
{% endblock footer %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/header.html
{% raw %}
{% comment %}
{% load cms_tags %}
{% endcomment %}
{% block header %}
<header>
</header>
{% endblock %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/menu.html
{% raw %}{% load i18n %}
{% load wagtail_menu %}
{% endraw %}{% if cookiecutter.multiple_languages == 'y' %}{% load wagtail_modeltranslation %}{% endif %}{% raw %}

{% endraw %}{% if cookiecutter.bootstrap_version == '3' %}{% raw %}

{% endraw %}{% if cookiecutter.cms == 'wagtail' %}{% raw %}
{% get_site_root as site_root %}
{% endraw %}{% endif %}{% raw %}

<div class="clearfix" id="{{menu_id}}-wrapper">
  <div class="navbar navbar-default {{class}}" role="navigation" id="{{menu_id}}">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#{{menu_id}}-navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Навигация</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          {% endraw %}{{ cookiecutter.project_slug }}{% raw %}
        </a>
        <span class="visible-xs navbar-brand">Главное меню</span>
      </div>

      <div class="collapse navbar-collapse" id="{{menu_id}}-navbar">
        <!--[if lt IE 9]>
          <ul class="nav navbar-nav">
        <![endif]-->
        <!--[if gte IE 9]>
          <ul class="nav navbar-nav nav-justified">
        <![endif]-->
        <![if !IE]>
        <ul class="navbar-nav-custom nav navbar-nav" itemscope itemtype="http://schema.org/SiteNavigationElement">
          <![endif]>
          {% endraw %}{% if cookiecutter.cms == 'None' %}{% raw %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% endraw %}{% elif cookiecutter.cms == 'wagtail' %}{% raw %}
            {% top_menu parent=site_root calling_page=self %}
          {% endraw %}{% endif %}{% raw %}
        </ul>
        
        {% endraw %}{% if cookiecutter.multiple_languages == 'y' %}
        {% if cookiecutter.cms == 'wagtail' %}
        {% raw %}
        <ul class="nav navbar-nav navbar-right">
          {% if request.LANGUAGE_CODE == 'ru' %}
            <a href="{% switch_language 'en' %}">English</a>
          {% else %}
            <a href="{% switch_language 'ru' %}">Russian</a>
          {% endif %}
        </ul>
        {% endraw %}{% endif %}{% endif %}{% raw %}
      </div>
    </div>
  </div>
</div>
{% endraw %}{%- elif cookiecutter.bootstrap_version == '4' %}{% raw %}
<nav class="navbar navbar-toggleable-md navbar-light bg-light">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {% endraw %}{% if cookiecutter.cms == 'None' %}{% raw %}
    <a class="navbar-brand" href="{% url 'home' %}">paramono</a>
  {% endraw %}{% endif %}{% raw %}

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto justify-content-center">
    {% endraw %}{% if cookiecutter.cms == 'None' %}{% raw %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
    {% endraw %}{% endif %}{% raw %}
      {% comment %}
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
        </li>
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
        </li>
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
        </li>
      {% endif %}
      {% endcomment %}
    </ul>
  </div>
</nav>
{% endraw %}{% endif %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/og.html
{% raw %}
{% comment %}
{% load cms_tags %}
{% endcomment %}

<meta property="og:url" content="{# https://paramono.com{{item.get_absolute_url}} #}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="{# {% page_attribute 'page_title' %} #}" />
<meta property="og:description" content="{# {% page_attribute 'meta_description' %} #}" />
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/og_image.html
{% raw %}
{% load static %}

{% static "core/img/logo_small.png" as logo_small %}
<meta property="og:image" content="https://st-volna.ru{{logo_small}}" />
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/blocks/tiles.html
{% raw %}

{% endraw %}{% if cookiecutter.cms == 'None' %}{% if cookiecutter.use_sorl_thumbnail == 'y' %}{% raw %}
{% load thumbnail %}
{% endraw %}{% endif %}{% endif %}{% raw %}

{% endraw %}{% if cookiecutter.cms == 'wagtail' %}{% raw %}
{% load wagtailcore_tags %}
{% endraw %}{% endif %}{% raw %}


<div class="row row-same-height">
  {% for object in objects %}
  <div class="col-12 col-sm-6 col-md-4 text-center">
    <div class="card same-height">
    {% endraw %}{% if cookiecutter.cms == 'None' %}{% if cookiecutter.use_sorl_thumbnail == 'y' %}{% raw %}
      {% if object.image %}
        {% thumbnail object.image "160x100" as im %}
        <div class="mb-2">
          <img class="img-fluid" src="{{im.url}}">
        </div>
        {% endthumbnail %}
      {% endif %}
    {% endraw %}{% endif %}{% endif %}{% raw %}

      {% endraw %}{% if cookiecutter.cms == 'wagtail' %}{% raw %}
      <h2 class="h6">
        <a href="{{ object.specific.url }}">
          {{object.specific.title}}
        </a>
      </h2>
      {% endraw %}{% else %}{% raw %}
      <h2 class="h6">
        <a href="{{ object.get_absolute.url }}">
          {{object.title}}
        </a>
      </h2>
      <p>{{object.short_description}}</p>
      {% endraw %}{% endif %}{% raw %}
    </div>
  </div>
  {% endfor %}
</div>
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/bootstrap4/field.html
{% raw %}
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/bootstrap4/layout/field_errors_block.html
{% raw %}
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/pages/about.html
{% raw %}{% extends "base.html" %}{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/users/user_detail.html
{% raw %}{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}
{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/users/user_form.html
{% raw %}{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}{% endraw %}

{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/users/user_list.html
{% raw %}{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}{% endraw %}